### ISSUE TITLE
A question about the paper

### ISSUE THREAD

**Issue by shuuchen** [hyBlue/FSRE-Depth#4]
Hi,

Thank you.
I have a question on equation 5 and 6 of the paper. In those equations, since both depths of i and j are normalized, they both become 1 or not ?

**Comment by hyBlue** [comment]
Hi, thanks for your interests.
In eq.5-6, we normalize the depth feature "vector", not the depth value and their norms become 1.
Thanks

**Comment by shuuchen** [comment]
Thanks.
You mean you normalize a pixel vector in the channel dimension, not the feature map in the spatial dimension, right ?

**Comment by hyBlue** [comment]
Yes. the feature vectors are normalized in their channel dimensions as below
https://github.com/hyBlue/FSRE-Depth/blob/d746866965204c37a072f3518dfd873df7ed2f1a/trainer_parallel.py#L148

Thanks

**Comment by shuuchen** [comment]
OK. 
So shouldn't you add (i) here, as in equation 5 or 6 ?
<img width="221" alt="スクリーンショット 2021-11-11 18 26 23" src="https://user-images.githubusercontent.com/13246825/141273053-0a9c65bb-ebd2-46e8-810e-04746dfe6206.png">

I also noticed that your attention map in equation 13 is not normalized by softmax, you normalized per-pixel attention value afterwards in a multi-embedding manner, right ? This is different with traditional methods.  Is it based on experiment results ? or did you also do experiments with traditional methods ?

**Comment by hyBlue** [comment]
A1.
![image](https://user-images.githubusercontent.com/30494126/141278756-30a007a6-29eb-487c-9a1c-9a1f5558f76a.png)

It actually means \hat(F^l_d(i)) = F^l_d(i) / ||F^l_d(i)|| and \hat(F^l_d(j)) = F^l_d(j) / ||F^l_d(i) || but I  omitted the indices for convenience. The equation may seem confusing but it's straightforward following the context because normalizing the whole feature maps doesn't make sense. 

A2.
The difference is that in the original multi-head attention, they compute attention scores (softmax) of "multiple inputs" through multiple heads. In contrast, we compute attention scores (softmax) of "multiple heads" to measure the significance of each 'head'. Also, we only use a single depth feature vector and a single segmentation feature vector for attention so there are no multiple 'inputs' to compute the attention as in the original way.

To apply original attention, we should change the settings into using multiple key for one query (e.g. compute one depth feature with multiple segmentation features in the local region), like other works that apply attention to vision tasks. I had experimented with it and have experimental results but it will take too long to explain because there too many stories about it. Anyway the current setting shows better result in my experiments.

Thanks

**Comment by shuuchen** [comment]
I see, you are doing pixel-wise local attention, not global reference attention. 
Thank you for the detail explanations.
