### ISSUE TITLE
About Semantic Segmentation Tags

### ISSUE THREAD

**Issue by joyqoo** [hyBlue/FSRE-Depth#8]
Hi, the labels I got using NIVDA's segmentation network are pseudo-labels for 19 categories, which are not the same as the pre-computed segmentation you uploaded

Could you please share your steps and practices?

Thank you very much!

**Comment by hyBlue** [comment]
Hi, thank you for your interest. The results I uploaded also have 19 categories, but the value is not in [0, 18]. You should map the label into the original class id used in cityscapes. 
You can refer to the below: 
https://github.com/hyBlue/FSRE-Depth/blob/8e762a4dda68ccbf6b59d94b217ebddf8666bb6d/utils/seg_utils.py#L27 
https://github.com/hyBlue/FSRE-Depth/blob/8e762a4dda68ccbf6b59d94b217ebddf8666bb6d/datasets/kitti_dataset.py#L233-L247

**Comment by hyBlue** [comment]
Please reopen it if you have more questions

**Comment by joyqoo** [comment]
Hi I want to train other datasets on this architecture

But the segmentation map generated by NIVDA is 19 categories and the KITTI segmentation map you provided is grayscale

I think it will error in get_seg_map Does your segmentation map do other preprocessing or just do class mapping in seg_utils?

Or do you have other suggestions for me? thanks

![005348](https://user-images.githubusercontent.com/30586145/165284627-de41f6f6-7b65-4ff8-bdc6-b252fd20c88d.png)

![0000000088](https://user-images.githubusercontent.com/30586145/165284604-94c7a10a-859e-49d3-a7d6-6a13d526b5f5.png)

![image](https://user-images.githubusercontent.com/30586145/165284973-8c403c31-df13-4828-9be8-2a3ba89a273e.png)

**Comment by hyBlue** [comment]
@joyqoo
I think you can run the code on your dataset after removing the below two lines:

https://github.com/hyBlue/FSRE-Depth/blob/8e762a4dda68ccbf6b59d94b217ebddf8666bb6d/datasets/kitti_dataset.py#L241-L242


Your labels are saved as 'trainid' and the labels I uploaded are saved as 'id'. My label generation procedure includes (run NVIDIA model -> convert outputs to 'id') since cityscapes segmentation requires 'id' for evaluation. (This is not a matter of my work nor NVIDIA's work, but just the dataset convention. 'trainid' and 'id' are described in seg_utils.py). Therefore, I need to convert 'id' to 'trainid' by running the two lines above. But it seems that you don't need those.
